// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mobqcaypvyboybcgkftl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vYnFjYXlwdnlib3liY2drZnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NjE3NDcsImV4cCI6MjA3NTMzNzc0N30.U1jSgnOyGm-YSzxPgWXVcwoJA4uJuw4NeUmo8801foQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});